config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GeoStat-Framework/GSTools:
      branch: main
      repo: https://github.com/GeoStat-Framework/GSTools
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GeoStat-Framework/GSTools git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-plum-indri.sh
        container: qc.acc_queasy-scarlet-uakari
  QC.Doc:
    repos:
      github.com/GeoStat-Framework/GSTools find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-teal-mongoose.sh
        container: qc.doc_cloudy-sangria-caracal
      github.com/GeoStat-Framework/GSTools git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-wisteria-shark.sh
        container: qc.doc_stinky-ochre-lemming
      github.com/GeoStat-Framework/GSTools markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-xanthic-okapi.sh
        container: qc.doc_hilly-olive-jaguar
      github.com/GeoStat-Framework/GSTools restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-emerald-shark.sh
        container: qc.doc_leaky-burgundy-budgerigar
  QC.Lic:
    repos:
      github.com/GeoStat-Framework/GSTools licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-khaki-starfish.sh
        container: qc.lic_stinky-cinnabar-dingo
  QC.Sec:
    repos:
      github.com/GeoStat-Framework/GSTools bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-chestnut-cockroach.sh
        container: qc.sec_snappy-teal-ferret
  QC.Sty:
    repos:
      github.com/GeoStat-Framework/GSTools flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-dandelion-crab.sh
        container: qc.sty_nerdy-mustard-kangaroo
      github.com/GeoStat-Framework/GSTools jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-puce-chamois.sh
        container: qc.sty_baggy-plum-whale
  QC.Uni:
    repos:
      github.com/GeoStat-Framework/GSTools pytest:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ruby-falcon.sh
        container: qc.uni_gummy-teal-dalmatian
  QC.Ver:
    repos:
      github.com/GeoStat-Framework/GSTools get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-apricot-swan.sh
        container: qc.ver_skimpy-chocolate-moorhen
timeout: 5400
